# typed: true

require 'action_controller/railtie'
require 'action_mailer/railtie'
require 'action_view/railtie'
require 'active_model/railtie'
require 'active_record/railtie'
require 'active_support/testing/time_helpers'
require 'bundler/setup'
require 'factory_bot_rails'
require 'rails'
require 'rake'
require 'rspec/rails'
require 'simplecov'
require 'sorbet-runtime'
